"""Add rich metadata and analytics tables

Revision ID: 811b676d774b
Revises: 
Create Date: 2026-07-03 21:07:14.785860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811b676d774b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_benchmarks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('coding_score', sa.Float(), nullable=True),
    sa.Column('reasoning_score', sa.Float(), nullable=True),
    sa.Column('math_score', sa.Float(), nullable=True),
    sa.Column('vision_score', sa.Float(), nullable=True),
    sa.Column('creative_score', sa.Float(), nullable=True),
    sa.Column('tool_score', sa.Float(), nullable=True),
    sa.Column('arena_score', sa.Float(), nullable=True),
    sa.Column('mmlu_score', sa.Float(), nullable=True),
    sa.Column('humaneval_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.Column('successful_requests', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_tokens_per_sec', sa.Float(), nullable=True),
    sa.Column('current_active_requests', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.drop_table('benchmarks')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supports_function_calling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('supports_json_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('context_window', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_output_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('max_output_tokens')
        batch_op.drop_column('context_window')
        batch_op.drop_column('supports_json_mode')
        batch_op.drop_column('supports_function_calling')

    op.create_table('benchmarks',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('model_id', sa.VARCHAR(), nullable=False),
    sa.Column('avg_latency_ms', sa.FLOAT(), nullable=True),
    sa.Column('success_rate', sa.FLOAT(), nullable=True),
    sa.Column('avg_quality_score', sa.FLOAT(), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('model_metrics')
    op.drop_table('model_benchmarks')
    # ### end Alembic commands ###
